### ISSUE TITLE
Using "from ete3 import NCBITaxa" cannot access NCBI

### ISSUE THREAD

**Issue by xiadawei123** [SysBioChalmers/HGTphyloDetect#13]
Hi，hank you for developing this tool. I encountered a problem when trying to extract NCBI taxa information. After troubleshooting, I found that the following commands caused the issue. I'm wondering if the NCBI taxa functionality in ete3 has become ineffective, especially for networks in mainland China.

from ete3 import NCBITaxa
ncbi = NCBITaxa()
ncbi.update_taxonomy_database()

error as show below：
NCBI database not present yet (first time used?)
Traceback (most recent call last):
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/http/client.py", line 1331, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/http/client.py", line 1377, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/http/client.py", line 1326, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/http/client.py", line 1085, in _send_output
    self.send(msg)
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/http/client.py", line 1029, in send
    self.connect()
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/http/client.py", line 1465, in connect
    super().connect()
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/http/client.py", line 995, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/socket.py", line 828, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/socket.py", line 963, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bioData/run_data2/xiazq/HGTphyloDetect-master/example/xzaq.py", line 2, in <module>
    ncbi = NCBITaxa()
           ^^^^^^^^^^
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 112, in __init__
    self.update_taxonomy_database(taxdump_file)
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 131, in update_taxonomy_database
    update_db(self.dbfile)
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 758, in update_db
    (md5_filename, _) = urlretrieve("https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz.md5")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/urllib/request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiazq/miniconda3/envs/HGT_analyses/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by le-yuan** [comment]
Exactly, you can try pip to reinstall your ete3 package, the command line is `pip install ete3`. Otherwise, you can try to resolve your issue by installing ete3 with different versions.
