### ISSUE TITLE
Is that a Bug?

### ISSUE THREAD

**Issue by wsh-1046** [SysBioChalmers/HGTphyloDetect#17]
Hi le-yuan:
When I was operating the step 
"python HGT_workflow_distant.py Nanorana_parkeri_SimID.faa", 
I got a problem,which show below:
Taxid by BLAST: 7917
Taxid by BLAST: 13616
Alien index: 299.19
This is a HGT event
Accession_id: AAP36269.1
Evalue: 1.16e-130
Traceback (most recent call last):
  File "~/HGT/HGTphyloDetect/main/HGT_workflow_distant.py", line 222, in <module>
    main()
  File "~/HGT/HGTphyloDetect/main/HGT_workflow_distant.py", line 196, in main
    taxid2name = ncbi.get_taxid_translator([ranks2lineage['phylum'], ranks2lineage['class'], ranks2lineage['superkingdom']])
                                            ~~~~~~~~~~~~~^^^^^^^^^^
Traceback (most recent call last):
  File "~/HGT/HGTphyloDetect/main/HGT_workflow_distant.py", line 222, in <module>
    main()
  File "~/HGT/HGTphyloDetect/main/HGT_workflow_distant.py", line 196, in main
    taxid2name = ncbi.get_taxid_translator([ranks2lineage['phylum'], ranks2lineage['class'], ranks2lineage['superkingdom']])
                                            ~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'phylum'
-----------------------------------------------------------------------------------------
Please tell me how to deal this problem. THANK YOU VERY MUCH!
BEST WISHES

**Comment by wsh-1046** [comment]
After I changed the script in HGT_workflow_distant.py in order to ignore the problem "KeyError:'phylum'",I have found that when I got into the next step,it would be interrupted often by the problem like this"This is gene 3------------------
XP_018426332.1
Yes, blast file already exists, nice!
Attention: please check the gene accession id!"
Please tell me how to deal with it.Thanks!

**Comment by huiifeng** [comment]
Dear Yuan

I am having the same issue, even though I am using a Genbank accession in my fasta file
Here is my genbank assession: QQS69424.1

I am having this error when I tried to run HGT_workflow_distant.py; for blastp.py is ok.

Could you help me with that?

Best regards
