### ISSUE TITLE
"NCBI database not present yet (first time used?)" followed by an error

### ISSUE THREAD

**Issue by DMatsliyah** [SysBioChalmers/HGTphyloDetect#6]
After running the example with
`python HGT_workflow.py input.fasta`

the following output and error received:
`
This is gene 1------------------
AAT92670
Yes, blast file already exists, nice!
NCBI database not present yet (first time used?)
Traceback (most recent call last):
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/http/client.py", line 1426, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/HGTphyloDetect/example/HGT_workflow.py", line 212, in <module>
    main()
  File "/HGTphyloDetect/example/HGT_workflow.py", line 90, in main
    ncbi = NCBITaxa()
  File "/.local/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 112, in __init__
    self.update_taxonomy_database(taxdump_file)
  File "/.local/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 131, in update_taxonomy_database
    update_db(self.dbfile)
  File "/.local/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 758, in update_db
    (md5_filename, _) = urlretrieve("https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz.md5")
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/apps/easybd/easybuild/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>
`

I don't see any reference to required databases and such in the readme or user guide.
any help would be appreciated :)

**Comment by le-yuan** [comment]
I will suggest you to upgrade your local NCBI taxonomy database. You can check the tutorial here: http://etetoolkit.org/docs/latest/tutorial/tutorial_ncbitaxonomy.html

It would be helpful if you run these three lines:
```
from ete3 import NCBITaxa
ncbi = NCBITaxa()
ncbi.update_taxonomy_database() 
```

**Comment by MCeelen** [comment]
It is likely that you already found a solution, but the problem may lie in a certificate issue with Python on Mac. You can solve it by following the solution in this stackexchange thread https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify.
